[versions]
kotlin = "2.1.20"
kotlin-coroutines = "1.10.2"
velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.20-R0.2-SNAPSHOT"
shadow = "8.3.3"
simplecloud-controller = "0.0.30-SNAPSHOT.2660ec8"
simplecloud-player = "0.0.1-SNAPSHOT.d490b2f"
paper = "1.21.4-R0.1-SNAPSHOT"
minotaur = "2.8.7"
sonatype-central-portal-publisher = "1.2.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
simplecloud-controller = { module = "app.simplecloud.controller:controller-api", version.ref = "simplecloud-controller" }
simplecloud-player = { module = "app.simplecloud.droplet.player:player-api", version.ref = "simplecloud-player" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonatype-central-portal-publisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "sonatype-central-portal-publisher" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
