[versions]
kotlin = "2.1.20"
kotlin-coroutines = "1.10.2"
shadow = "8.3.3"
openapi-generator = "7.14.0"

jnats = "2.21.2"
controller-proto = "32.0.0.1.20251125160757.798bafd5010c"
okhttp = "4.12.0"
okhttp-logging = "4.12.0"
gson = "2.13.1"
gson-fire = "1.9.0"
jakarta-annotation = "2.1.1"
javax-annotation = "1.3.2"

velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.21-R0.4"
paper = "1.21.4-R0.1-SNAPSHOT"

minotaur = "2.8.7"
sonatype-central-portal-publisher = "1.2.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }

jnats = { module = "io.nats:jnats", version.ref = "jnats" }
controller-proto = { module = "build.buf.gen:simplecloud_controller_protocolbuffers_java_lite", version.ref = "controller-proto" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gson-fire = { module = "io.gsonfire:gson-fire", version.ref = "gson-fire" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
javax-annotation = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonatype-central-portal-publisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "sonatype-central-portal-publisher" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
